
CREATE TABLE IF NOT EXISTS users(
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    passwordHash VARCHAR(60) NOT NULL,
    publicKey TEXT NOT NULL,
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS friends(
    id SERIAL PRIMARY KEY,
    userId INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    friendId INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(10) NOT NULL,
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS messages(
    id BIGSERIAL PRIMARY KEY,
    fromUser INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    toUser INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    iv BYTEA NOT NULL,
    encryptedKey BYTEA NOT NULL,
    ciphertext BYTEA NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    delivered BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS refreshTokens(
    id SERIAL PRIMARY KEY,
    token VARCHAR(255) UNIQUE NOT NULL,
    userId INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expiresAt TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS userStatus(
    userId INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    isOnline BOOLEAN NOT NULL DEFAULT FALSE,
    lastSeen TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);